defaults:
  - _self_
  - data: cap24_W18
  - evaluation: all
  - model: resnet
  - dataloader: ten_sec

gpu: 2
gpu_ids: [0, 1, 2]  # gpus to use if multi_gpu==true
multi_gpu: false

model_path: ".../3-Model/_finetuning/_model/tmp/fold0/tmp.pt"
report_root: ".../_model/"
is_verbose: True

output_prefix: "cap24_W18"
add_classical_feats: False

known_min_mag: 0.92
obj_spr_lambda: 1