## baselines
## Pre-trained flip-net fine-tuned fine tune all layers

feat_hand_crafted: false
feat_random_cnn: false

# trained networks
model_path: /data/UKBB/SSL/day_sec_10k/logs/models
flip_net_path: "/data/UKBB/SSL/final_models/three_tasks/mtl_best.mdl"
input_size: 300  # input size after resampling the raw data
subR: 1

# hyper-parameters
learning_rate: 0.0001
num_workers: 6
patience: 10
num_epoch: 200 # default 200

evaluation_name: mtssl_finetuning


